#!/usr/bin/env bash

docker run \
  -i \
  -t \
  --rm \
  --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_' | grep -v PATH) \
  -v "$PWD":/project \
  electronuserland/builder:wine \
  /bin/bash -c 'env \
  && apt-get update \
  && apt-get install -y --allow-unauthenticated \
    automake \
    libgconf-2-4 \
    libtool \
    libxext-dev \
    libxkbfile-dev \
    libxtst-dev \
  && npm install \
  && npm test \
  && npm run release -- --linux --win'
